### ISSUE TITLE
Sonar WebDriver Plugin should not installable via Marketplace for SonarQube in Version 6.7.5 (build 38563)

### ISSUE THREAD

**Issue by chrisstornowski** [kwoding/sonar-webdriver-plugin#1]
This plugin is using SonarQube API in Version 7.2.1 and this will lead to an exception while starting SonarQube in Version 6.7.5 (build 38563)

```
java.lang.NoClassDefFoundError: org/sonar/api/rule/RuleScope
        at it.ding.sonar.config.WebDriverRulesDefinition.addMetadata(WebDriverRulesDefinition.java:87)
        at it.ding.sonar.config.WebDriverRulesDefinition.ruleMetadata(WebDriverRulesDefinition.java:74)
        at it.ding.sonar.config.WebDriverRulesDefinition.newRule(WebDriverRulesDefinition.java:63)
        at it.ding.sonar.config.WebDriverRulesDefinition.define(WebDriverRulesDefinition.java:43)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:56)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:83)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:80)
        at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
        at org.sonar.server.platform.Platform.access$400(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.sonar.api.rule.RuleScope
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 32 common frames omitted

```

So this plugin should be marked for SonarQube above 6.7.5 (build 38563) and should not be displayed for installing in Marketplace for SonarQube in version 6.7.5 (build 38563).

**Comment by kwoding** [comment]
Thank you for your post, fixed it in version 1.0.3. This will soon be published to the Marketplace.
Details of the change: the RuleScope is defaulted to "all" in version 7.1, so no need to set it so it is also compatible with 6.7
